"""add new_comers and tithe_offering to attendance

Revision ID: 2223aa87da25
Revises: d9543240a67e
Create Date: 2025-12-23 18:06:14.955079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2223aa87da25'
down_revision = 'd9543240a67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_comers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tithe_offering', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('attendance')]

    with op.batch_alter_table('attendance') as batch_op:
        if 'tithe_offering' in columns:
            batch_op.drop_column('tithe_offering')
        if 'new_comers' in columns:
            batch_op.drop_column('new_comers')
            
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('attendance', schema=None) as batch_op:
#         batch_op.drop_column('tithe_offering')
#         batch_op.drop_column('new_comers')

    # ### end Alembic commands ###
