"""remove unique constraint from states code

Revision ID: 6038264e2d1f
Revises: 84596b633bda
Create Date: 2025-11-16 20:30:42.772137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6038264e2d1f'
down_revision = '84596b633bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('districts_code_key'), type_='unique')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('groups_code_key'), type_='unique')

    with op.batch_alter_table('old_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('old_groups_code_key'), type_='unique')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('regions_code_key'), type_='unique')

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('states_code_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('states_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('regions_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('old_groups', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('old_groups_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('groups_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('districts_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
