"""Restructure hierarchy

Revision ID: 84596b633bda
Revises: eb69c78064b8
Create Date: 2025-11-13 19:20:36.061294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84596b633bda'
down_revision = 'eb69c78064b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('district_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
