"""Add leader email and phone to hierarchy tables

Revision ID: ca6deaaf27ce
Revises: 2223aa87da25
Create Date: 2026-01-08 22:16:35.284786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6deaaf27ce'
down_revision = '2223aa87da25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('leader_phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('leader_phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('old_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('leader_phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('leader_phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('leader_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_column('leader_phone')
        batch_op.drop_column('leader_email')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_column('leader_phone')
        batch_op.drop_column('leader_email')

    with op.batch_alter_table('old_groups', schema=None) as batch_op:
        batch_op.drop_column('leader_phone')
        batch_op.drop_column('leader_email')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('leader_phone')
        batch_op.drop_column('leader_email')

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_column('leader_phone')
        batch_op.drop_column('leader_email')

    # ### end Alembic commands ###
