"""Restructure hierarchy

Revision ID: eb69c78064b8
Revises: 9245a3539aae
Create Date: 2025-11-13 18:43:59.589693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb69c78064b8'
down_revision = '9245a3539aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youth_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_type', sa.String(length=50), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('old_group_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('member_boys', sa.Integer(), nullable=True),
    sa.Column('member_girls', sa.Integer(), nullable=True),
    sa.Column('visitor_boys', sa.Integer(), nullable=True),
    sa.Column('visitor_girls', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('male', sa.Integer(), nullable=True),
    sa.Column('female', sa.Integer(), nullable=True),
    sa.Column('testimony', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('solutions', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['old_group_id'], ['old_groups.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_group_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'old_groups', ['old_group_id'], ['id'])
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_group_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('groups_district_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'old_groups', ['old_group_id'], ['id'])
        batch_op.drop_column('district_id')

    with op.batch_alter_table('old_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('old_groups_district_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('old_groups_group_id_fkey'), type_='foreignkey')
        batch_op.drop_column('district_id')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('old_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('old_groups_group_id_fkey'), 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('old_groups_district_id_fkey'), 'districts', ['district_id'], ['id'])

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('groups_district_id_fkey'), 'districts', ['district_id'], ['id'])
        batch_op.drop_column('old_group_id')

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')
        batch_op.drop_column('old_group_id')

    op.drop_table('youth_attendance')
    # ### end Alembic commands ###
